runtime: nodejs16

env_variables:
  DB_HOST: 34.101.244.133
  DB_PORT: 5432
  DB_USER: postgres
  DB_PASS: aicarejuara
  DB_NAME: aicare
  JWT_SECRET: aicare123

beta_settings:
  # The connection name of your instance, available by using
  # 'gcloud beta sql instances describe [INSTANCE_NAME]' or from
  # the Instance details page in the Google Cloud Platform Console.
  cloud_sql_instances: aicare-development:asia-southeast2:aicare-psql